//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsolaWebService.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost", ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento city del espacio de nombres http://localhost no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/getTemperature", ReplyAction="*")]
        TestConsolaWebService.ServiceReference1.getTemperatureResponse getTemperature(TestConsolaWebService.ServiceReference1.getTemperatureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/getTemperature", ReplyAction="*")]
        System.Threading.Tasks.Task<TestConsolaWebService.ServiceReference1.getTemperatureResponse> getTemperatureAsync(TestConsolaWebService.ServiceReference1.getTemperatureRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTemperatureRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTemperature", Namespace="http://localhost", Order=0)]
        public TestConsolaWebService.ServiceReference1.getTemperatureRequestBody Body;
        
        public getTemperatureRequest() {
        }
        
        public getTemperatureRequest(TestConsolaWebService.ServiceReference1.getTemperatureRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost")]
    public partial class getTemperatureRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string city;
        
        public getTemperatureRequestBody() {
        }
        
        public getTemperatureRequestBody(string city) {
            this.city = city;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTemperatureResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTemperatureResponse", Namespace="http://localhost", Order=0)]
        public TestConsolaWebService.ServiceReference1.getTemperatureResponseBody Body;
        
        public getTemperatureResponse() {
        }
        
        public getTemperatureResponse(TestConsolaWebService.ServiceReference1.getTemperatureResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost")]
    public partial class getTemperatureResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double getTemperatureResult;
        
        public getTemperatureResponseBody() {
        }
        
        public getTemperatureResponseBody(double getTemperatureResult) {
            this.getTemperatureResult = getTemperatureResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : TestConsolaWebService.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<TestConsolaWebService.ServiceReference1.WebService1Soap>, TestConsolaWebService.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestConsolaWebService.ServiceReference1.getTemperatureResponse TestConsolaWebService.ServiceReference1.WebService1Soap.getTemperature(TestConsolaWebService.ServiceReference1.getTemperatureRequest request) {
            return base.Channel.getTemperature(request);
        }
        
        public double getTemperature(string city) {
            TestConsolaWebService.ServiceReference1.getTemperatureRequest inValue = new TestConsolaWebService.ServiceReference1.getTemperatureRequest();
            inValue.Body = new TestConsolaWebService.ServiceReference1.getTemperatureRequestBody();
            inValue.Body.city = city;
            TestConsolaWebService.ServiceReference1.getTemperatureResponse retVal = ((TestConsolaWebService.ServiceReference1.WebService1Soap)(this)).getTemperature(inValue);
            return retVal.Body.getTemperatureResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestConsolaWebService.ServiceReference1.getTemperatureResponse> TestConsolaWebService.ServiceReference1.WebService1Soap.getTemperatureAsync(TestConsolaWebService.ServiceReference1.getTemperatureRequest request) {
            return base.Channel.getTemperatureAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestConsolaWebService.ServiceReference1.getTemperatureResponse> getTemperatureAsync(string city) {
            TestConsolaWebService.ServiceReference1.getTemperatureRequest inValue = new TestConsolaWebService.ServiceReference1.getTemperatureRequest();
            inValue.Body = new TestConsolaWebService.ServiceReference1.getTemperatureRequestBody();
            inValue.Body.city = city;
            return ((TestConsolaWebService.ServiceReference1.WebService1Soap)(this)).getTemperatureAsync(inValue);
        }
    }
}
